name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Se activa cuando envías cambios a la rama main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install and Build
        run: |
          npm install
          npm run build
        env:
          VITE_GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }} # Opcional: si quieres usar la IA en la web

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Sube la carpeta dist que generamos arriba
          branch: gh-pages # La sube a esta rama especial
